### ISSUE TITLE
Add cacher.

### ISSUE THREAD

**Issue by coollog** [GoogleCloudPlatform/minikube-build-tools-for-java#52]
Caches all layers (content and diffId) and last modified times for the application layers.

Cache the base image manifest as well to know to not repull the base image.

- [x] Metadata #56 
- [x] Metadata JSON template #70 
- [x] Translator for metadata JSON #71 
- [x] Initialize cache with root directory #71 
- [x] Cache writer #79
- [x] Cache checker #81 
- [x] Cacher reader #82
- [x] Cache pruner? (TODO for https://github.com/GoogleCloudPlatform/minikube-build-tools-for-java/issues/111)
