### ISSUE TITLE
Add registry API client.

### ISSUE THREAD

**Issue by coollog** [GoogleCloudPlatform/minikube-build-tools-for-java#59]
- [x] image manifest puller #68 
- [x] blob puller https://github.com/GoogleCloudPlatform/minikube-build-tools-for-java/pull/85
- [x] image manifest pusher #88 
- [x] blob pusher #93
- [x] blob existence checker #108 
- [x] authentication method retriever #95
